In [390]:
import pandas as pd
import numpy as np

In [391]:
df = pd.read_csv('dataset/survey_results_public.csv')
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,2.850000e+05,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,2.500000e+05,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.560000e+05,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1.320000e+06,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89179,89180,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Bootstrapping a business;Freelance/contr...,"Associate degree (A.A., A.S., etc.)",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,20,5,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,NaN,Brazil,BRL\tBrazilian real,2.000000e+05,HTML/CSS;Java;JavaScript;SQL;TypeScript,Bash/Shell (all shells);C;Go;HTML/CSS;JavaScri...,MongoDB;MySQL;PostgreSQL;SQLite,PostgreSQL;SQLite,Digital Ocean;Firebase;Google Cloud;Heroku;Vercel,Amazon Web Services (AWS);Heroku;Netlify;Vercel,Angular;AngularJS;Express;jQuery;Node.js;Nuxt....,Express;Node.js;Nuxt.js;Svelte;Vue.js,Flutter,NaN,Chocolatey;CMake;Docker;Maven (build tool);npm...,Docker;npm;Pip;Vite;Yarn,Android Studio;Atom;Eclipse;IntelliJ IDEA;Netb...,Visual Studio Code,Android;Windows,Android;Ubuntu;Windows,Asana;Confluence;Jira;Markdown File;Miro;Notio...,Markdown File;Miro;Wikis,Discord;Google Meet;Jitsi;Microsoft Teams;Slac...,Discord;Google Meet;Jitsi;Microsoft Teams;Tele...,ChatGPT,ChatGPT,Whispr AI,Whispr AI,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,Neutral,NaN,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Learning about a codebase;Project planning;Wri...,Writing code;Documenting code;Debugging and ge...,Deployment and monitoring,NaN,NaN,NaN,NaN,Writing code;Documenting code;Debugging and ge...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89180,89181,I agree,I am a developer by profession,18-24 years old,"Student, full-time;Employed, part-time","Hybrid (some remote, some in-person)",School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,NaN,5,NaN,"Developer, back-end",NaN,NaN,Investigate,Start a free trial;Ask developers I know/work ...,Romania,NaN,NaN,Dart;Java;Python;SQL,Java;JavaScript;Python;SQL;TypeScript,PostgreSQL,PostgreSQL,NaN,NaN,Spring Boot,Spring Boot,Flutter;Opencv;RabbitMQ;Spring Framework;Torch...,RabbitMQ;Spring Framework;Torch/PyTorch,Maven (build tool);Pip,Maven (build tool);Pip,Android Studio;IntelliJ IDEA;PyCharm,IntelliJ IDEA;PyCharm,Windows,Windows,Jira,Jira,Microsoft Teams,Microsoft Teams,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"No, not really",I'm not sure,Yes,Very favorable,Speed up learning,Somewhat trust,Writing code;Documenting code;Testing code,Learning about a codebase;Debugging and gettin...,Project planning;Committing and reviewing code...,NaN,NaN,NaN,NaN,Learning about a codebase;Debugging and gettin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
89181,89182,I agree,I code primarily as a hobby,Prefer not to say,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Hackathons (virtual or ...,NaN,Codecademy;Coursera,10,NaN,NaN,NaN,NaN,NaN,NaN,Israel,NaN,NaN,Assembly;Bash/Shell (all shells);C;C#;Python;R...,Python;Rust,SQLite,NaN,Amazon Web Services (AWS),Amazon Web Services (AWS);Microsoft Azure,NaN,NaN,NumPy;Pandas;TensorFlow,NumPy;Pandas;Torch/PyTorch,Cargo,Cargo;Docker;Kubernetes;Terraform,Jupyter Notebook/JupyterLab;Neovim;Visual Stud...,Jupyter Notebook/JupyterLab;Neovim;Visual Stud...,Windows,NaN,NaN,NaN,NaN,NaN,ChatGPT;Quora Poe,ChatGPT;Quora Poe,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,"No, but I plan to soon",Very favorable,NaN,Highly trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
89182,89183,I agree,I am a developer by profession,Under 18 years old,"Employed, part-time;Student, part-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Secondary school (e.g. American high school, G...",Online Courses or Certification;Other online r...,Formal documentation provided by the owner of ...,Udemy,3,NaN,System administrator,NaN,NaN,Investigate,Ask developers I know/work with;Visit develope...,Switzerland,NaN,NaN,Bash/Shell (all shells);C#;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);HTML/CSS;JavaScript;Po...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Red...,Cassandra;Cosmos DB;Dynamodb;MariaDB;Microsoft...,Amazon Web Services (AWS);Cloudflare;Google Cl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Next.js;Node.js;React;WordPress,Angular;AngularJS;Express;Next.js;Node.js;Reac...,CUDA;NumPy;Torch/PyTorch,CUDA;Flutter;NumPy;TensorFlow;Torch/PyTorch,Docker;Kubernetes;npm;Podman;Vite,Ansible;APT;Docker;Kubernetes;npm;Pip;Podman;T...,Eclipse;IntelliJ IDEA;Nano;Notepad++;PyCharm;V...,Jupyter Notebook/JupyterLab;Notepad++;Visual S...,Arch;Debian;iOS;iPadOS;MacOS;Ubuntu;Windows;Wi...,BSD;Red Hat;Solaris;Ubuntu;Windows,Confluence;Jira;Trello,Azure Devops;Confluence;Jira,Cisco Webex Teams;Discord;Microsoft Teams;Sign...,Discord;Microsoft Teams;Skype,Bing AI;ChatGPT;WolframAlpha,Bing AI;ChatGPT;Google Bard AI,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,No,NaN,"Yes, somewhat",Define Parameters more detailed. I believe in ...,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat distrust,Learning about a codebase;Project planning;Wri...,Learning about a codebase;Writing code;Debuggi...,Committing and reviewing code,NaN,Debugging and getting help;Deployment and moni...,NaN,NaN,Learning about a codebase;Writing code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
89183,89184,I agree,I am a developer by profession,35-44 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Online Courses or Certification;Othe...,Formal documentation provided by the owner of ...,Codecademy;Pluralsight;Coursera,17,12,"Developer, full-stack",100 to 499 employees,I have some influence,NaN,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,3.300000e+09,C#;Go;JavaScript;SQL;TypeScript,C#;Go;JavaScript;SQL;TypeScript,Microsoft SQL Server;Redis;SQLite,Microsoft SQL Server;Redis;SQLite,Hetzner,Hetzner;Microsoft Azure,Angular;ASP.NET;ASP.NET CORE;Blazor;Node.js,Angular;ASP.NET;ASP.NET CORE;Blazor;Deno;Node....,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+) ;Apache Kafka;RabbitMQ;Tauri,Docker;npm;NuGet;pnpm;Vite;Webpack;Yarn,Bun;Docker;npm;NuGet;pnpm;Vite;Yarn,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,NaN,NaN,Google Meet;Skype;Telegram;Whatsapp,Google Meet;Skype;Telegram;Whatsapp,ChatGPT,ChatGPT,GitHub Copilot,GitHub Copilot,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Neither trust nor distrust,Learning about a codebase;Writing code,Learning about a codebase;Writing code,NaN,Learning about a codebase,NaN,NaN,NaN,Writing code,Yes,People manager,14.0,Agree,Neither agree nor disagree,Neither agree nor disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,30-60 minutes a day,DevOps function;Developer portal or other cent...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN

In [392]:
print((df.shape))

(89184, 84)

In [393]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  str
 2   MainBranch                           89184 non-null  str
 3   Age                                  89184 non-null  str
 4   Employment                           87898 non-null  str
 5   RemoteWork                           73810 non-null  str
 6   CodingActivities                     73764 non-null  str
 7   EdLevel                              87973 non-null  str
 8   LearnCode                            87663 non-null  str
 9   LearnCodeOnline                      70084 non-null  str
 10  LearnCodeCoursesCert                 37076 non-null  str
 11  YearsCode                            87435 non-null  str
 12  YearsCodePro                         66136 non-null  str
 13  DevType                              76872 non-null  str
 14  OrgSize                              65043 non-null  str
 15  PurchaseInfluence                    64964 non-null  str
 16  TechList                             60851 non-null  str
 17  BuyNewTool                           83009 non-null  str
 18  Country                              87973 non-null  str
 19  Currency                             65334 non-null  str
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  str
 22  LanguageWantToWorkWith               80709 non-null  str
 23  DatabaseHaveWorkedWith               73435 non-null  str
 24  DatabaseWantToWorkWith               60911 non-null  str
 25  PlatformHaveWorkedWith               63628 non-null  str
 26  PlatformWantToWorkWith               51308 non-null  str
 27  WebframeHaveWorkedWith               66938 non-null  str
 28  WebframeWantToWorkWith               56741 non-null  str
 29  MiscTechHaveWorkedWith               57019 non-null  str
 30  MiscTechWantToWorkWith               46848 non-null  str
 31  ToolsTechHaveWorkedWith              77884 non-null  str
 32  ToolsTechWantToWorkWith              68315 non-null  str
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  str
 34  NEWCollabToolsWantToWorkWith         76649 non-null  str
 35  OpSysPersonal use                    86557 non-null  str
 36  OpSysProfessional use                78587 non-null  str
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  str
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  str
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  str
 40  OfficeStackSyncWantToWorkWith        69776 non-null  str
 41  AISearchHaveWorkedWith               56328 non-null  str
 42  AISearchWantToWorkWith               46150 non-null  str
 43  AIDevHaveWorkedWith                  25904 non-null  str
 44  AIDevWantToWorkWith                  19587 non-null  str
 45  NEWSOSites                           87973 non-null  str
 46  SOVisitFreq                          87140 non-null  str
 47  SOAccount                            87852 non-null  str
 48  SOPartFreq                           66061 non-null  str
 49  SOComm                               87692 non-null  str
 50  SOAI                                 47858 non-null  str
 51  AISelect                             87973 non-null  str
 52  AISent                               61501 non-null  str
 53  AIAcc                                38594 non-null  str
 54  AIBen                                61396 non-null  str
 55  AIToolInterested in Using            32783 non-null  str
 56  AIToolCurrently Using                36137 non-null  str
 57  AIToolNot interested in Using        21069 non-null  str
 58  AINextVery different                 12661 non-null  str
 59  AINextNeither different nor similar  6599 non-null   str
 60  AINextSomewhat similar               6238 non-null   str
 61  AINextVery similar                   2621 non-null   str
 62  AINextSomewhat different             23303 non-null  str
 63  TBranch                              65768 non-null  str
 64  ICorPM                               43668 non-null  str
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  str
 67  Knowledge_2                          41670 non-null  str
 68  Knowledge_3                          41798 non-null  str
 69  Knowledge_4                          41684 non-null  str
 70  Knowledge_5                          41527 non-null  str
 71  Knowledge_6                          41520 non-null  str
 72  Knowledge_7                          41467 non-null  str
 73  Knowledge_8                          41404 non-null  str
 74  Frequency_1                          41916 non-null  str
 75  Frequency_2                          41925 non-null  str
 76  Frequency_3                          41054 non-null  str
 77  TimeSearching                        42778 non-null  str
 78  TimeAnswering                        42629 non-null  str
 79  ProfessionalTech                     41783 non-null  str
 80  Industry                             36774 non-null  str
 81  SurveyLength                         86485 non-null  str
 82  SurveyEase                           86554 non-null  str
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), str(80)
memory usage: 57.2 MB
None

In [394]:
pd.set_option('display.max_columns',84)
df.head(10)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
5,6,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,Other,21,21,"Developer, back-end",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,78000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,Go;Rust,BigQuery;Cloud Firestore;PostgreSQL;Redis,NaN,Amazon Web Services (AWS);Cloudflare;Google Cloud,NaN,Angular;Express;NestJS;Node.js,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;pnpm;Terraform,Cargo,Helix;Neovim,NaN,Other (Please Specify):,MacOS,Jira;Markdown File;Notion;Stack Overflow for T...,NaN,Google Meet;Microsoft Teams;Slack;Zoom,NaN,ChatGPT;Google Bard AI;Neeva AI,NaN,GitHub Copilot;Tabnine,NaN,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Favorable,Greater efficiency,Somewhat trust,Learning about a codebase;Documenting code;Tes...,Writing code;Debugging and getting help,Project planning,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,22.0,Agree,Strongly agree,Disagree,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,Disagree,Disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
6,7,I agree,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,Udemy,4,3,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,NaN,Ask developers I know/work with;Read ratings o...,United States of America,USD\tUnited States dollar,135000.0,Ada;Clojure;Elixir;Go;HTML/CSS;Java;JavaScript...,NaN,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Datomic,Amazon Web Services (AWS);Digital Ocean,Vercel,AngularJS;jQuery;Node.js;Phoenix;Ruby on Rails...,NaN,RabbitMQ;Spring Framework,NaN,Bun;Cargo;Chocolatey;Docker;Homebrew;Kubernete...,NaN,Emacs;IntelliJ IDEA;RubyMine;Visual Studio Cod...,NaN,MacOS;Windows,MacOS,Jira,NaN,Slack,NaN,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Neutral,Yes,Unfavorable,Improve accuracy in coding,Somewhat distrust,NaN,Writing code;Debugging and getting help,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,4.0,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
7,8,I agree,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Codecademy;edX,5,3,"Developer, full-stack",10 to 19 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,80000.0,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,Elixir;Go;Julia;Python;R;Rust;Scala;SQL;TypeSc...,Dynamodb;MongoDB;MySQL;Redis;SQLite,BigQuery;Cockroachdb;DuckDB;Elasticsearch;Mong...,Amazon Web Services (AWS);Fly.io;Netlify;Vercel,Amazon Web Services (AWS);Digital Ocean;Fly.io...,Angular;Express;Next.js;Node.js;React,Deno;FastAPI;Fastify;Flask;NestJS;Next.js;Node...,NumPy;Pandas;Scikit-Learn;Tauri;TensorFlow,.NET MAUI;Apache Kafka;Apache Spark;Hugging Fa...,Ansible;Cargo;Docker;Homebrew;Make;npm;Pip;pnp...,Cargo;Dagger;Docker;Homebrew;Kubernetes;Make;n...,DataGrip;IPython;Neovim;Vim;Visual Studio Code,IPython;Neovim;RStudio;Visual Studio Code,MacOS;Ubuntu;Windows,MacOS;Ubuntu;Windows,Markdown File;Notion,Markdown File;Notion,Microsoft Teams,Discord,Bing AI;ChatGPT;Google Bard AI,ChatGPT;Neeva AI;Perplexity AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Speed up learning,Somewhat distrust,Project planning;Writing code;Documenting code...,Project planning;Writing code;Debugging and ge...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
8,9,I agree,"I am not primarily a developer, but I write co...",45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,Udemy;Pluralsight,20,15,System administrator,100 to 499 employees,I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,Finland,EUR European Euro,60000.0,C#;JavaScript;PowerShell;Ruby;TypeScript,C#;Ruby;Rust;TypeScript,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;PostgreSQL;SQLite,Digital Ocean;Microsoft Azure;Netlify,Digital Ocean;Microsoft Azure;Netlify,ASP.NET CORE;Next.js;React;Ruby on Rails,ASP.NET CORE;Qwik;Ruby on Rails;Svelte,.NET (5+),.NET (5+),Chocolatey;Docker;Homebrew;MSBuild;npm;NuGet;p...,Homebrew;pnpm;Vite,Neovim;Visual Studio Code,Neovim;Visual Studio Code,MacOS;Ubuntu,Ubuntu;Windows;Windows Subsystem for Linux (WSL),Azure Devops;Microsoft Lists;Microsoft Planner,Azure Devops,Discord;Microsoft Teams;Slack,Discord;Microsoft Teams,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,To suggest solutions in alternative language f...,Yes,Very favorable,Increase productivity,Somewhat trust,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,64254.0
9,10,I agree,I am a developer by profession,25-34 years old,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Udemy;Pluralsight;Coursera;Udacity,6,NaN,"Developer, full-stack",NaN,NaN,Investigate,Start a free trial;Research companies that hav...,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;Firebase Realtime Database;Mon...,Amazon Web Services (AWS);Firebase;Google Clou...,Cloudflare;Firebase;Google Cloud;IBM Cloud Or ...,Angular;Express;NestJS;React,Deno;Express;FastAPI;Fastify;NestJS;Qwik;React...,NaN,NaN,Docker;npm;Vite;Webpack;Yarn,Docker;npm;Podman;Vite;Webpack;Yarn,Visual Studio Code,Visual Studio Code,Fedora;Other Linux-based;Ubuntu;Windows;Window...,Fedora;Other Linux-based;Red Hat;Windows;Windo...,Asana;Markdown File;Miro;Notion;Redmine;Trello,Asana;Markdown File;Miro;Notion;Redmine;Trello,Discord;Google Chat;Google Meet;Slack;Telegram,Discord;Google Chat;Google Meet;Telegram,Bing AI;ChatGPT,Bing AI;ChatGPT;Google Bard AI,AWS CodeWhisperer;GitHub Copilot;Tabnine,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,AI could assist solving communication issues p...,Yes,Indifferent,Other (please explain);Increase productivity;G...,Neither trust nor distrust,Learning about a codebase;Documenting code;Com...,Writing code;Debugging and getting help,Project planning;Testing code;Deployment and m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN

In [395]:
schema_df = pd.read_csv('dataset/survey_results_schema.csv')
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID310,Q310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
3,QID312,Q120,,True,MC,SAVR
4,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...,...
73,QID289,Knowledge_7,Waiting on answers to questions often causes i...,NaN,MC,MAVR
74,QID289,Knowledge_8,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
75,QID290,Frequency_1,Needing help from people outside of your immed...,NaN,MC,MAVR
76,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [396]:
print(list(schema_df.columns))

['qid', 'qname', 'question', 'force_resp', 'type', 'selector']

In [397]:
print(schema_df['qname'])
print(type(schema_df['qname']))

0              S0
1        MetaInfo
2            Q310
3            Q120
4              S1
         ...
73    Knowledge_7
74    Knowledge_8
75    Frequency_1
76    Frequency_2
77    Frequency_3
Name: qname, Length: 78, dtype: str
<class 'pandas.Series'>

In [398]:
schema_df[["question","type"]]

                                             question  type
0   <div><span style="font-size:19px;"><strong>Hel...    DB
1                                   Browser Meta Info  Meta
2   <div><span style="font-size:19px;"><strong>You...    DB
3                                                        MC
4   <span style="font-size:22px; font-family: aria...    DB
..                                                ...   ...
73  Waiting on answers to questions often causes i...    MC
74  I feel like I have the tools and/or resources ...    MC
75  Needing help from people outside of your immed...    MC
76  Interacting with people outside of your immedi...    MC
77  Encountering knowledge silos (where one indivi...    MC

[78 rows x 2 columns]

In [399]:
print(type(schema_df[["question","type"]]))

<class 'pandas.DataFrame'>

In [400]:
schema_df['question'].loc[4]

'<span style="font-size:22px; font-family: arial,helvetica,sans-serif; font-weight: 700;">Basic Information</span><br>\n<br>\n<p><span style="font-size:16px; font-family:arial,helvetica,sans-serif;">The first section will focus on some basic information about who you are.<br>\n<br>\nMost questions in this section are required. Required questions are noted with *.</span></p>'

In [401]:
schema_df.iloc[:2,[0,1,2]]

     qid     qname                                           question
0  QID16        S0  <div><span style="font-size:19px;"><strong>Hel...
1  QID12  MetaInfo                                  Browser Meta Info

In [402]:
schema_df.loc[[0,1,2],["qid","qname"]]

      qid     qname
0   QID16        S0
1   QID12  MetaInfo
2  QID310      Q310

Now i want to know how much are from USA.

In [403]:
country_arr = np.array(df["Country"])

country_arr = country_arr[country_arr == "United States of America"]
print(country_arr.size)

18647

In [404]:
pd.set_option('display.max_rows',10)

df["Country"].value_counts()

Country
United States of America                                18647
Germany                                                  7328
India                                                    5625
United Kingdom of Great Britain and Northern Ireland     5552
Canada                                                   3507
                                                        ...
Saint Kitts and Nevis                                       1
Marshall Islands                                            1
Samoa                                                       1
Central African Republic                                    1
San Marino                                                  1
Name: count, Length: 185, dtype: int64

Indexing

In [405]:
schema_df.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   qid         78 non-null     str
 1   qname       78 non-null     str
 2   question    78 non-null     str
 3   force_resp  67 non-null     object
 4   type        78 non-null     str
 5   selector    78 non-null     str
dtypes: object(1), str(5)
memory usage: 3.8+ KB
<class 'pandas.DataFrame'>
RangeIndex: 89184 entries, 0 to 89183
Data columns (total 84 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   ResponseId                           89184 non-null  int64
 1   Q120                                 89184 non-null  str
 2   MainBranch                           89184 non-null  str
 3   Age                                  89184 non-null  str
 4   Employment                           87898 non-null  str
 5   RemoteWork                           73810 non-null  str
 6   CodingActivities                     73764 non-null  str
 7   EdLevel                              87973 non-null  str
 8   LearnCode                            87663 non-null  str
 9   LearnCodeOnline                      70084 non-null  str
 10  LearnCodeCoursesCert                 37076 non-null  str
 11  YearsCode                            87435 non-null  str
 12  YearsCodePro                         66136 non-null  str
 13  DevType                              76872 non-null  str
 14  OrgSize                              65043 non-null  str
 15  PurchaseInfluence                    64964 non-null  str
 16  TechList                             60851 non-null  str
 17  BuyNewTool                           83009 non-null  str
 18  Country                              87973 non-null  str
 19  Currency                             65334 non-null  str
 20  CompTotal                            48225 non-null  float64
 21  LanguageHaveWorkedWith               87140 non-null  str
 22  LanguageWantToWorkWith               80709 non-null  str
 23  DatabaseHaveWorkedWith               73435 non-null  str
 24  DatabaseWantToWorkWith               60911 non-null  str
 25  PlatformHaveWorkedWith               63628 non-null  str
 26  PlatformWantToWorkWith               51308 non-null  str
 27  WebframeHaveWorkedWith               66938 non-null  str
 28  WebframeWantToWorkWith               56741 non-null  str
 29  MiscTechHaveWorkedWith               57019 non-null  str
 30  MiscTechWantToWorkWith               46848 non-null  str
 31  ToolsTechHaveWorkedWith              77884 non-null  str
 32  ToolsTechWantToWorkWith              68315 non-null  str
 33  NEWCollabToolsHaveWorkedWith         85864 non-null  str
 34  NEWCollabToolsWantToWorkWith         76649 non-null  str
 35  OpSysPersonal use                    86557 non-null  str
 36  OpSysProfessional use                78587 non-null  str
 37  OfficeStackAsyncHaveWorkedWith       69090 non-null  str
 38  OfficeStackAsyncWantToWorkWith       53743 non-null  str
 39  OfficeStackSyncHaveWorkedWith        83439 non-null  str
 40  OfficeStackSyncWantToWorkWith        69776 non-null  str
 41  AISearchHaveWorkedWith               56328 non-null  str
 42  AISearchWantToWorkWith               46150 non-null  str
 43  AIDevHaveWorkedWith                  25904 non-null  str
 44  AIDevWantToWorkWith                  19587 non-null  str
 45  NEWSOSites                           87973 non-null  str
 46  SOVisitFreq                          87140 non-null  str
 47  SOAccount                            87852 non-null  str
 48  SOPartFreq                           66061 non-null  str
 49  SOComm                               87692 non-null  str
 50  SOAI                                 47858 non-null  str
 51  AISelect                             87973 non-null  str
 52  AISent                               61501 non-null  str
 53  AIAcc                                38594 non-null  str
 54  AIBen                                61396 non-null  str
 55  AIToolInterested in Using            32783 non-null  str
 56  AIToolCurrently Using                36137 non-null  str
 57  AIToolNot interested in Using        21069 non-null  str
 58  AINextVery different                 12661 non-null  str
 59  AINextNeither different nor similar  6599 non-null   str
 60  AINextSomewhat similar               6238 non-null   str
 61  AINextVery similar                   2621 non-null   str
 62  AINextSomewhat different             23303 non-null  str
 63  TBranch                              65768 non-null  str
 64  ICorPM                               43668 non-null  str
 65  WorkExp                              43579 non-null  float64
 66  Knowledge_1                          42535 non-null  str
 67  Knowledge_2                          41670 non-null  str
 68  Knowledge_3                          41798 non-null  str
 69  Knowledge_4                          41684 non-null  str
 70  Knowledge_5                          41527 non-null  str
 71  Knowledge_6                          41520 non-null  str
 72  Knowledge_7                          41467 non-null  str
 73  Knowledge_8                          41404 non-null  str
 74  Frequency_1                          41916 non-null  str
 75  Frequency_2                          41925 non-null  str
 76  Frequency_3                          41054 non-null  str
 77  TimeSearching                        42778 non-null  str
 78  TimeAnswering                        42629 non-null  str
 79  ProfessionalTech                     41783 non-null  str
 80  Industry                             36774 non-null  str
 81  SurveyLength                         86485 non-null  str
 82  SurveyEase                           86554 non-null  str
 83  ConvertedCompYearly                  48019 non-null  float64
dtypes: float64(3), int64(1), str(80)
memory usage: 57.2 MB

In [406]:
schema_df.set_index('qname')

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
Q120,QID312,,True,MC,SAVR
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [407]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID310,Q310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
3,QID312,Q120,,True,MC,SAVR
4,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...,...
73,QID289,Knowledge_7,Waiting on answers to questions often causes i...,NaN,MC,MAVR
74,QID289,Knowledge_8,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
75,QID290,Frequency_1,Needing help from people outside of your immed...,NaN,MC,MAVR
76,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [408]:
schema_df.index

RangeIndex(start=0, stop=78, step=1)

In [409]:
schema_df.set_index("qname",inplace = True)

In [410]:
schema_df

,qid,question,force_resp,type,selector
qname,,,,,
S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
Q120,QID312,,True,MC,SAVR
S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...
Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [411]:
schema_df.nunique() #ignoring NaN

qid           67
question      78
force_resp     2
type           6
selector       8
dtype: int64

In [412]:
schema_df['force_resp'].unique()

array([False, True, nan], dtype=object)

In [413]:
schema_df['force_resp'].nunique()

2

In [414]:
schema_df.index

Index(['S0', 'MetaInfo', 'Q310', 'Q120', 'S1', 'MainBranch', 'Age',
       'Employment', 'RemoteWork', 'CodingActivities', 'S2', 'EdLevel',
       'LearnCode', 'LearnCodeOnline', 'LearnCodeCoursesCert', 'YearsCode',
       'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'TechList',
       'BuyNewTool', 'Country', 'Currency', 'CompTotal', 'S3', 'Language',
       'Database', 'Platform', 'Webframe', 'MiscTech', 'ToolsTech',
       'NEWCollabTools', 'OpSys', 'OfficeStackAsync', 'OfficeStackSync',
       'AISearch', 'AIDev', 'S4', 'NEWSOSites', 'SOVisitFreq', 'SOAccount',
       'SOPartFreq', 'SOComm', 'S5', 'SOAI', 'AISelect', 'AISent', 'AIAcc',
       'AIBen', 'AITool', 'AINext', 'AIOpen', 'S6', 'TBranch', 'ICorPM',
       'WorkExp', 'Knowledge', 'Frequency', 'TimeSearching', 'TimeAnswering',
       'ProfessionalTech', 'Industry', 'SOTeamsUsage', 'S7', 'SurveyLength',
       'SurveyEase', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3',
       'Knowledge_4', 'Knowledge_5', 'Knowledge_6', 'Knowledge_7',
       'Knowledge_8', 'Frequency_1', 'Frequency_2', 'Frequency_3'],
      dtype='str', name='qname')

In [415]:
schema_df.loc["Country",["qid","question","force_resp"]]

qid                                                        QID6
question      Where do you live? <span style="font-weight: b...
force_resp                                                 True
Name: Country, dtype: object

In [416]:
schema_df.iloc[0] # iloc will still work even after changing indexing

qid                                                       QID16
question      <div><span style="font-size:19px;"><strong>Hel...
force_resp                                                False
type                                                         DB
selector                                                     TB
Name: S0, dtype: object

In [417]:
schema_df.reset_index(inplace = True)

In [418]:
schema_df.index

RangeIndex(start=0, stop=78, step=1)

Filtering

In [419]:
filt = schema_df["force_resp"]==True
print(filt)

0     False
1     False
2     False
3      True
4     False
      ...
73    False
74    False
75    False
76    False
77    False
Name: force_resp, Length: 78, dtype: bool

In [420]:
schema_df[filt]

,qname,qid,question,force_resp,type,selector
3,Q120,QID312,,True,MC,SAVR
5,MainBranch,QID2,Which of the following options best describes ...,True,MC,SAVR
6,Age,QID127,What is your age? *,True,MC,MAVR
11,EdLevel,QID25,Which of the following best describes the high...,True,MC,SAVR
22,Country,QID6,"Where do you live? <span style=""font-weight: b...",True,MC,DL
23,Currency,QID50,Which currency do you use day-to-day? If your ...,True,MC,DL
39,NEWSOSites,QID266,Which of the following Stack Overflow sites ha...,True,MC,MAVR
46,AISelect,QID314,Do you currently use AI tools in your developm...,True,MC,SAVR
54,TBranch,QID299,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR

In [421]:
schema_df.loc[filt,["qname","question"]]

         qname                                           question
3         Q120
5   MainBranch  Which of the following options best describes ...
6          Age                                What is your age? *
11     EdLevel  Which of the following best describes the high...
22     Country  Where do you live? <span style="font-weight: b...
23    Currency  Which currency do you use day-to-day? If your ...
39  NEWSOSites  Which of the following Stack Overflow sites ha...
46    AISelect  Do you currently use AI tools in your developm...
54     TBranch  <span style="font-size:16px;">Would you like t...

In [422]:
schema_df.loc[(schema_df["force_resp"]==True) & (schema_df["selector"]=="DL"),["qname","question"]]

       qname                                           question
22   Country  Where do you live? <span style="font-weight: b...
23  Currency  Which currency do you use day-to-day? If your ...

In [423]:
df.loc[((df["CompTotal"]>100000) & (df["Country"].isin(["India"])) & (df["LanguageHaveWorkedWith"].str.contains("Python",na = False)) ),["Age","EdLevel","LanguageHaveWorkedWith","DevType","ToolsTechHaveWorkedWith","CompTotal"]].head(20)

,Age,EdLevel,LanguageHaveWorkedWith,DevType,ToolsTechHaveWorkedWith,CompTotal
209,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Assembly;Bash/Shell (all shells);C;C++;Dart;HT...,"Developer, full-stack",Cargo;Docker;Nix;npm;NuGet;Pacman;Pip;pnpm;Vit...,3000000.0
271,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",C;C++;Dart;HTML/CSS;Java;JavaScript;Python;SQL...,"Developer, back-end",APT;Docker;GNU GCC;npm,420000.0
314,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",C;C++;Python;Rust,"Developer, back-end",Ansible;Pacman,300000.0
377,35-44 years old,Some college/university study without earning ...,Bash/Shell (all shells);HTML/CSS;Java;JavaScri...,"Developer, full-stack",Ant;Gradle;Kubernetes;Make;Maven (build tool),2500000.0
397,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",C;C++;Go;HTML/CSS;Python;Rust;SQL;TypeScript,"Developer, embedded applications or devices",Cargo;CMake;Kubernetes;Make;Vite,1050000.0
...,...,...,...,...,...,...
1459,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",C;Go;HTML/CSS;Kotlin;Python;SQL,"Engineer, data",Cargo;Docker;npm,180000.0
1665,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Dart;HTML/CSS;Java;JavaScript;Kotlin;PowerShel...,"Developer, full-stack",npm,2000000.0
1817,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Java;JavaScript;Python;Scala;SQL,"Developer, back-end",Docker;Maven (build tool);Pip;Terraform,4000000.0
1904,18-24 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Python,Data scientist or machine learning specialist,Docker,3000000.0
2555,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",HTML/CSS;JavaScript;Python;TypeScript,"Developer, front-end",Docker;npm;pnpm;Vite,400000.0

Renaming Column

In [424]:
print(type(schema_df.columns))
schema_df.columns = [x.upper() for x in schema_df.columns]
print(type(schema_df.columns))
schema_df.head(2)

<class 'pandas.Index'>
<class 'pandas.Index'>

,QNAME,QID,QUESTION,FORCE_RESP,TYPE,SELECTOR
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser

In [425]:
schema_df.columns = schema_df.columns.str.capitalize()
schema_df.head(2)

,Qname,Qid,Question,Force_resp,Type,Selector
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser

In [426]:
schema_df.rename(columns = {"Force_resp" : "Force resp"},inplace= True)
schema_df.head(2)

,Qname,Qid,Question,Force resp,Type,Selector
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser

Row Update

In [427]:
def age_checker (age_dtls : str) :
    ls = age_dtls.split("years")
    return ls[0]
  

df['Age'] = df['Age'].apply(age_checker)
df.head(10)

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,I agree,None of these,18-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I agree,I am a developer by profession,25-34,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Other,18,9,"Senior Executive (C-Suite, VP, etc.)",2 to 9 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,285000.0,HTML/CSS;JavaScript;Python,Bash/Shell (all shells);C#;Dart;Elixir;GDScrip...,Supabase,Firebase Realtime Database;Supabase,Amazon Web Services (AWS);Netlify;Vercel,Fly.io;Netlify;Render,Next.js;React;Remix;Vue.js,Deno;Elm;Nuxt.js;React;Svelte;Vue.js,Electron;React Native;Tauri,Capacitor;Electron;Tauri;Uno Platform;Xamarin,Docker;Kubernetes;npm;Pip;Vite;Webpack;Yarn,Godot;npm;pnpm;Unity 3D;Unreal Engine;Vite;Web...,Vim;Visual Studio Code,Vim;Visual Studio Code,iOS;iPadOS;MacOS;Windows;Windows Subsystem for...,MacOS;Windows;Windows Subsystem for Linux (WSL),Asana;Basecamp;GitHub Discussions;Jira;Linear;...,GitHub Discussions;Linear;Notion;Trello,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord;Signal;Slack;Zoom,ChatGPT,ChatGPT;Neeva AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per month or weekly,"Yes, definitely","I don't think it's super necessary, but I thin...",Yes,Indifferent,Other (please explain),Somewhat distrust,Learning about a codebase;Writing code;Debuggi...,Writing code;Committing and reviewing code,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,10.0,Strongly agree,Agree,Strongly agree,Agree,Agree,Agree,Agree,Strongly agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,285000.0
2,3,I agree,I am a developer by profession,45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Professional development or self-paced l...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,27,23,"Developer, back-end","5,000 to 9,999 employees",I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,250000.0,Bash/Shell (all shells);Go,Haskell;OCaml;Rust,NaN,NaN,Amazon Web Services (AWS);Google Cloud;OpenSta...,NaN,NaN,NaN,NaN,NaN,Cargo;Docker;Kubernetes;Make;Nix,Cargo;Kubernetes;Nix,Emacs;Helix,Emacs;Helix,MacOS;Other Linux-based,MacOS;Other Linux-based,Markdown File;Stack Overflow for Teams,Markdown File,Microsoft Teams;Slack;Zoom,Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,23.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,Agree,6-10 times a week,6-10 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Microservices;Automated testin...,"Information Services, IT, Software Development...",Appropriate in length,Easy,250000.0
3,4,I agree,I am a developer by profession,25-34,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Colleague;Friend or family member;Other online...,Formal documentation provided by the owner of ...,NaN,12,7,"Developer, front-end",100 to 499 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,156000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,PostgreSQL;Redis,PostgreSQL;Redis,Cloudflare;Heroku,Cloudflare;Heroku,Node.js;React;Ruby on Rails;Vue.js;WordPress,Node.js;Ruby on Rails;Vue.js,NaN,NaN,Homebrew;npm;Vite;Webpack;Yarn,Homebrew;npm;Vite,IntelliJ IDEA;Vim;Visual Studio Code;WebStorm,IntelliJ IDEA;Vim;WebStorm,iOS;iPadOS;MacOS,iOS;iPadOS;MacOS,Jira,Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Slack;Zoom,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",I'm wearing of Stack Overflow using AI.,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Automated testing;Continuous integration (CI) ...,NaN,Appropriate in length,Easy,156000.0
4,5,I agree,I am a developer by profession,25-34,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;Codecademy;edX,6,4,"Developer, full-stack",20 to 99 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Philippines,PHP\tPhilippine peso,1320000.0,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,BigQuery;Elasticsearch;MongoDB;PostgreSQL,Elasticsearch;MongoDB;PostgreSQL;Redis;Supabase,Amazon Web Services (AWS);Firebase;Heroku;Netl...,Amazon Web Services (AWS);Cloudflare;Digital O...,Express;Gatsby;NestJS;Next.js;Node.js;React,Express;NestJS;Next.js;Node.js;React;Remix;Vue.js,NaN,NaN,Docker;npm;Webpack;Yarn,Docker;npm;Yarn,Vim;Visual Studio Code,Vim;Visual Studio Code,Other (Please Specify):,Other (Please Specify):,Confluence;Jira;Notion,Confluence;Jira;Notion,Discord;Google Meet;Slack;Zoom,Discord;Google Meet;Slack;Zoom,ChatGPT,ChatGPT,NaN,NaN,Stack Overflow;Stack Exchange,A few times per week,No,NaN,Neutral,Using AI to suggest better answer to my questi...,Yes,Very favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,Project planning;Testing code;Committing and r...,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,6.0,Agree,Strongly agree,Agree,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Microservices;Automated testing;Observability ...,Other,Appropriate in length,Neither easy nor difficult,23456.0
5,6,I agree,I am a developer by profession,35-44,"Employed, full-time",Remote,Hobby;Professional development or self-paced l...,Some college/university study without earning ...,Books / Physical media;Colleague;Online Course...,Formal documentation provided by the owner of ...,Other,21,21,"Developer, back-end",100 to 499 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,78000.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Ru...,Go;Rust,BigQuery;Cloud Firestore;PostgreSQL;Redis,NaN,Amazon Web Services (AWS);Cloudflare;Google Cloud,NaN,Angular;Express;NestJS;Node.js,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;pnpm;Terraform,Cargo,Helix;Neovim,NaN,Other (Please Specify):,MacOS,Jira;Markdown File;Notion;Stack Overflow for T...,NaN,Google Meet;Microsoft Teams;Slack;Zoom,NaN,ChatGPT;Google Bard AI;Neeva AI,NaN,GitHub Copilot;Tabnine,NaN,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Favorable,Greater efficiency,Somewhat trust,Learning about a codebase;Documenting code;Tes...,Writing code;Debugging and getting help,Project planning,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,22.0,Agree,Strongly agree,Disagree,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,Disagree,Disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,DevOps function;Microservices;Observability to...,Other,Appropriate in length,Neither easy nor difficult,96828.0
6,7,I agree,I am a developer by profession,35-44,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Profe...,Some college/university study without earning ...,Friend or family member;Online Courses or Cert...,NaN,Udemy,4,3,"Developer, full-stack","1,000 to 4,999 employees",I have little or no influence,NaN,Ask developers I know/work with;Read ratings o...,United States of America,USD\tUnited States dollar,135000.0,Ada;Clojure;Elixir;Go;HTML/CSS;Java;JavaScript...,NaN,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Datomic,Amazon Web Services (AWS);Digital Ocean,Vercel,AngularJS;jQuery;Node.js;Phoenix;Ruby on Rails...,NaN,RabbitMQ;Spring Framework,NaN,Bun;Cargo;Chocolatey;Docker;Homebrew;Kubernete...,NaN,Emacs;IntelliJ IDEA;RubyMine;Visual Studio Cod...,NaN,MacOS;Windows,MacOS,Jira,NaN,Slack,NaN,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,Neutral,Yes,Unfavorable,Improve accuracy in coding,Somewhat distrust,NaN,Writing code;Debugging and getting help,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,4.0,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,3-5 times a week,1-2 times a week,Less than 15 minutes a day,15-30 minutes a day,Microservices;Automated testing;Continuous int...,"Information Services, IT, Software Development...",Appropriate in length,Easy,135000.0
7,8,I agree,I am a developer by profession,25-34,"Employed, full-time",Remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Codecademy;edX,5,3,"Developer, full-stack",10 to 19 employees,I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,80000.0,Go;HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,Elixir;Go;Julia;Python;R;Rust;Scala;SQL;TypeSc...,Dynamodb;MongoDB;MySQL;Redis;SQLite,BigQuery;Cockroachdb;DuckDB;Elasticsearch;Mong...,Amazon Web Services (AWS);Fly.io;Netlify;Vercel,Amazon Web Services (AWS);Digital Ocean;Fly.io...,Angular;Express;Next.js;Node.js;React,Deno;FastAPI;Fastify;Flask;NestJS;Next.js;Node...,NumPy;Pandas;Scikit-Learn;Tauri;TensorFlow,.NET MAUI;Apache Kafka;Apache Spark;Hugging Fa...,Ansible;Cargo;Docker;Homebrew;Make;npm;Pip;pnp...,Cargo;Dagger;Docker;Homebrew;Kubernetes;Make;n...,DataGrip;IPython;Neovim;Vim;Visual Studio Code,IPython;Neovim;RStudio;Visual Studio Code,MacOS;Ubuntu;Windows,MacOS;Ubuntu;Windows,Markdown File;Notion,Markdown File;Notion,Microsoft Teams,Discord,Bing AI;ChatGPT;Google Bard AI,ChatGPT;Neeva AI;Perplexity AI,GitHub Copilot,GitHub Copilot,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,A few times per month or weekly,"Yes, somewhat",NaN,Yes,Favorable,Increase productivity;Speed up learning,Somewhat distrust,Project planning;Writing code;Documenting code...,Project planning;Writing code;Debugging and ge...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60-120 minutes a day,30-60 minutes a day,None of these,Financial Services,NaN,NaN,80000.0
8,9,I agree,"I am not primarily a developer, but I write co...",45-54,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Online Courses or Certification;On the job tra...,Formal documentation provided by the owner of ...,Udemy;Pluralsight,20,15,System administrator,100 to 499 employees,I have some influence,Given a list,Start a free trial;Ask developers I know/work ...,Finland,EUR European Euro,60000.0,C#;JavaScript;PowerShell;Ruby;TypeScript,C#;Ruby;Rust;TypeScript,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,MariaDB;Microsoft SQL Server;PostgreSQL;SQLite,Digital Ocean;Microsoft Azure;Netlify,Digital Ocean;Microsoft Azure;Netlify,ASP.NET CORE;Next.js;React;Ruby on Rails,ASP.NET CORE;Qwik;Ruby on Rails;Svelte,.NET (5+),.NET (5+),Chocolatey;Docker;Homebrew;MSBuild;npm;NuGet;p...,Homebrew;pnpm;Vite,Neovim;Visual Studio Code,Neovim;Visual Studio Code,MacOS;Ubuntu,Ubuntu;Windows;Windows Subsystem for Linux (WSL),Azure Devops;Microsoft Lists;Microsoft Planner,Azure Devops,Discord;Microsoft Teams;Slack,Discord;Microsoft Teams,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,To suggest solutions in alternative language f...,Yes,Very favorable,Increase productivity,Somewhat trust,Learning about a codebase;Writing code;Documen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,64254.0
9,10,I agree,I am a developer by profession,25-34,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,edX;Udemy;Pluralsight;Coursera;Udacity,6,NaN,"Developer, full-stack",NaN,NaN,Investigate,Start a free trial;Research companies that hav...,India,NaN,NaN,HTML/CSS;Java;JavaScript;Python;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;Firebase Realtime Database;Mon...,Amazon Web Services (AWS);Firebase;Google Clou...,Cloudflare;Firebase;Google Cloud;IBM Cloud Or ...,Angular;Express;NestJS;React,Deno;Express;FastAPI;Fastify;NestJS;Qwik;React...,NaN,NaN,Docker;npm;Vite;Webpack;Yarn,Docker;npm;Podman;Vite;Webpack;Yarn,Visual Studio Code,Visual Studio Code,Fedora;Other Linux-based;Ubuntu;Windows;Window...,Fedora;Other Linux-based;Red Hat;Windows;Windo...,Asana;Markdown File;Miro;Notion;Redmine;Trello,Asana;Markdown File;Miro;Notion;Redmine;Trello,Discord;Google Chat;Google Meet;Slack;Telegram,Discord;Google Chat;Google Meet;Telegram,Bing AI;ChatGPT,Bing AI;ChatGPT;Google Bard AI,AWS CodeWhisperer;GitHub Copilot;Tabnine,AWS CodeWhisperer;GitHub Copilot,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Neutral,AI could assist solving communication issues p...,Yes,Indifferent,Other (please explain);Increase productivity;G...,Neither trust nor distrust,Learning about a codebase;Documenting code;Com...,Writing code;Debugging and getting help,Project planning;Testing code;Deployment and m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN

In [428]:
schema_df

,Qname,Qid,Question,Force resp,Type,Selector
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
3,Q120,QID312,,True,MC,SAVR
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

In [429]:
schema_df.loc[schema_df['Force resp'] == True,'Force resp'] = schema_df.loc[schema_df['Force resp'] == True,'Force resp'].replace({True : False})

schema_df

,Qname,Qid,Question,Force resp,Type,Selector
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB
3,Q120,QID312,,False,MC,SAVR
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR

Column delete or add

In [430]:
schema_df['qid_name'] = schema_df['Qid']+"-"+schema_df['Qname']
schema_df

,Qname,Qid,Question,Force resp,Type,Selector,qid_name
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB,QID16-S0
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser,QID12-MetaInfo
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB,QID310-Q310
3,Q120,QID312,,False,MC,SAVR,QID312-Q120
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB,QID1-S1
...,...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR,QID289-Knowledge_7
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR,QID289-Knowledge_8
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR,QID290-Frequency_1
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR,QID290-Frequency_2
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR,QID290-Frequency_3

In [431]:
schema_df[['Q','QNO']]=schema_df['Qid'].str.split('QID',expand=True)
schema_df

,Qname,Qid,Question,Force resp,Type,Selector,qid_name,Q,QNO
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB,QID16-S0,,16
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser,QID12-MetaInfo,,12
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB,QID310-Q310,,310
3,Q120,QID312,,False,MC,SAVR,QID312-Q120,,312
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB,QID1-S1,,1
...,...,...,...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR,QID289-Knowledge_7,,289
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR,QID289-Knowledge_8,,289
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR,QID290-Frequency_1,,290
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR,QID290-Frequency_2,,290
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR,QID290-Frequency_3,,290

In [432]:
schema_df.drop(columns=['qid_name','Q'],inplace= True)
schema_df

,Qname,Qid,Question,Force resp,Type,Selector,QNO
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB,16
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser,12
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB,310
3,Q120,QID312,,False,MC,SAVR,312
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB,1
...,...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR,289
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR,289
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR,290
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR,290
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR,290

Row insert or Delete

In [433]:
schema_df = pd.concat([schema_df,pd.DataFrame([{"qid" : "QID99"}])],ignore_index= True)
schema_df

,Qname,Qid,Question,Force resp,Type,Selector,QNO,qid
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB,16,NaN
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser,12,NaN
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB,310,NaN
3,Q120,QID312,,False,MC,SAVR,312,NaN
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB,1,NaN
...,...,...,...,...,...,...,...,...
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR,289,NaN
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR,290,NaN
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR,290,NaN
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR,290,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,QID99

In [434]:

schema_df.drop(index = schema_df.loc[schema_df["qid"] == "QID99"].index , inplace=True)
schema_df

,Qname,Qid,Question,Force resp,Type,Selector,QNO,qid
0,S0,QID16,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB,16,NaN
1,MetaInfo,QID12,Browser Meta Info,False,Meta,Browser,12,NaN
2,Q310,QID310,"<div><span style=""font-size:19px;""><strong>You...",False,DB,TB,310,NaN
3,Q120,QID312,,False,MC,SAVR,312,NaN
4,S1,QID1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB,1,NaN
...,...,...,...,...,...,...,...,...
73,Knowledge_7,QID289,Waiting on answers to questions often causes i...,NaN,MC,MAVR,289,NaN
74,Knowledge_8,QID289,I feel like I have the tools and/or resources ...,NaN,MC,MAVR,289,NaN
75,Frequency_1,QID290,Needing help from people outside of your immed...,NaN,MC,MAVR,290,NaN
76,Frequency_2,QID290,Interacting with people outside of your immedi...,NaN,MC,MAVR,290,NaN
77,Frequency_3,QID290,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR,290,NaN

Sorting

In [435]:
df['CompTotal'].sort_values() #YearsCode

88949    0.0
28649    0.0
28915    0.0
28575    0.0
8998     0.0
        ...
89173    NaN
89176    NaN
89180    NaN
89181    NaN
89182    NaN
Name: CompTotal, Length: 89184, dtype: float64

In [436]:
df.sort_values(by = ['CompTotal','YearsCode'],ascending=[False,True],inplace= True)

In [437]:
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
56322,56323,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Boots...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,More than 50 years,More than 50 years,Blockchain,"10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Bahamas,AED United Arab Emirates dirham,5.000000e+46,Ada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,"No, not at all",SEX,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
18463,18464,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,NaN,NaN,11,8,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+21,Bash/Shell (all shells);Python,Bash/Shell (all shells);Go;JavaScript;Python,PostgreSQL;Redis,Elasticsearch;MongoDB;PostgreSQL;Redis,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud,FastAPI,FastAPI,NaN,NaN,Composer;Docker,Composer;Docker,IPython;PyCharm;Vim,IPython;PyCharm;Vim,Ubuntu,Ubuntu,Jira;Trello,Jira;Trello,Discord;Google Meet;Jitsi;Skype;Slack;Telegram...,Discord;Google Meet;Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,11.0,Strongly agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,6-10 times a week,NaN,30-60 minutes a day,30-60 minutes a day,Microservices;Continuous integration (CI) and ...,NaN,Appropriate in length,Easy,NaN
49553,49554,I agree,"I am not primarily a developer, but I write co...",25-34,"Employed, full-time",In-person,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,22,5,Research & Development role,"1,000 to 4,999 employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.000000e+16,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,CUDA;GTK;NumPy;Pandas;Qt;Scikit-Learn;TensorFl...,CMake;Docker;Make;MSVC;Ninja;Pip,CMake;LLVM's Clang;Make;Pip,Notepad++;Spyder;Vim;Visual Studio Code,Notepad++;Spyder;Vim;Visual Studio Code,Debian;Windows,Red Hat;Windows,Markdown File;Redmine,Markdown File;Redmine,Microsoft Teams,Microsoft Teams,WolframAlpha,ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",It would be most helpful if the AI could delet...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Continuous i...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN
43556,43557,I agree,I am a developer by profession,18-24,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Pluralsight,8,4,"Developer, desktop or enterprise applications",500 to 999 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,Romania,RON\tRomanian leu,1.000000e+16,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,BigQuery;Cosmos DB;Elasticsearch;MariaDB;Micro...,NaN,Amazon Web Services (AWS);Microsoft Azure;VMware,Microsoft Azure;VMware,ASP.NET;ASP.NET CORE,NaN,.NET (5+) ;GTK;MFC;Opencv;OpenGL;Qt,GTK;MFC;Opencv;OpenGL;Qt,Ant;APT;Boost.Test;CMake;cppunit;Dagger;Docker...,Boost.Test;CMake;cppunit;GNU GCC;LLVM's Clang;...,Atom;Code::Blocks;Kate;Nano;Notepad++;Qt Creat...,Kate;Qt Creator;Visual Studio,Cygwin;Ubuntu;Windows,Ubuntu,GitHub Discussions;Markdown File,GitHub Discussions,IRC;Microsoft Teams;Skype,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Less than once per month or monthly,Yes,Less than once per month or monthly,Neutral,don't,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
35779,35780,I agree,I am a developer by profession,25-34,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Pluralsight;Coursera;Udacity,10,7,NaN,20 to 99 employees,I have a great deal of influence,Investigate,Ask developers I know/work with;Visit develope...,Canada,CAD\tCanadian dollar,1.000000e+15,Assembly;Bash/Shell (all shells);C#;C++;Cobol;...,HTML/CSS;SQL;TypeScript,Cloud Firestore;Elasticsearch;MariaDB;Microsof...,MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,Angular;AngularJS;ASP.NET;ASP.NET CORE;Deno;Ex...,Angular;NestJS,Electron,NaN,Chocolatey;CMake;Composer;Docker;Gradle;npm;We...,Docker;npm,Android Studio;Atom;Eclipse;Goland;IntelliJ ID...,Visual Studio Code,Android;Ubuntu;Windows;Windows Subsystem for L...,Android;Red Hat;Ubuntu;Windows;Windows Subsyst...,Azure Devops;Confluence;Jira;Markdown File;Trello,NaN,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,none,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88883,88884,I agree,I am a developer by profession,18-24,"Employed, full-time",Remote,Freelance/contract work,"Secondary school (e.g. American high school, G...",Friend or family member,NaN,NaN,NaN,NaN,Other (please specify):,10 to 19 employees,I have a great deal of influence,Given a list,Ask developers I know/work with,Antigua and Barbuda,AOA\tAngolan kwanza,NaN,Ada;Clojure;Cobol,Apex;APL;Assembly;Bash/Shell (all shells);C;C#,BigQuery,NaN,NaN,NaN,WordPress,NaN,.NET MAUI,NaN,NaN,NaN,NaN,NaN,NaN,AIX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,A few times per month or weekly,No,NaN,Neutral,"Create a chat bot like chat gpt , to get answe...",Yes,Very favorable,Increase productivity,Highly trust,Project planning;Documenting code,Learning about a codebase;Project planning;Wri...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,Yes,People manager,50.0,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times a week,3-5 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,Microservices,Financial Services,Appropriate in length,NaN,NaN
88940,88941,I agree,I am learning to code,Under 18,NaN,NaN,NaN,Something else,"Other online resources (e.g., videos, blogs, f...","How-to videos;Online challenges (e.g., daily o...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,Chile,NaN,NaN,HTML/CSS;Python;SQL,C#,NaN,NaN,NaN,NaN,Node.js,NaN,NaN,NaN,npm,NaN,Visual Studio Code,NaN,Windows,NaN,NaN,NaN,Discord;Telegram;Whatsapp,NaN,ChatGPT,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,No,NaN,"No, not at all",NaN,"No, but I plan to soon",NaN,NaN,Somewhat trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN
89028,89029,I agree,None of these,45-54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89134,89135,I agree,I code primarily as a hobby,Under 18,"Student, full-time",NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);C;C++;Elixir;Go;Haskel...,Assembly;Bash/Shell (all shells);C;Clojure;Eli...,Cloud Firestore;Dynamodb;Firebase Realtime Dat...,Cassandra;Cockroachdb;Elasticsearch;MongoDB;Ne...,Amazon Web Services (AWS);Cloudflare;Digital O...,Amazon Web Services (AWS);Cloudflare;Google Cl...,Angular;Deno;Django;Express;Flask;Next.js;Node...,Angular;FastAPI;Fastify;Next.js;Node.js;Nuxt.j...,Electron;Keras;NumPy;Opencv;Pandas;Qt;SwiftUI;...,Hadoop;Ionic;Keras;NumPy;Opencv;Pandas;SwiftUI...,Ansible;APT;Cargo;Docker;GNU GCC;Make;npm;Terr...,Ansible;APT;Cargo;Docker;GNU GCC;Kubernetes;Ma...,Neovim;Vim;Xcode,Neovim;Vim;Xcode,MacOS,MacOS,Airtable;Markdown File;Notion,Markdown File;Notion,Discord;Google Chat;Google Meet;Zoom,Discord,ChatGPT;Google Bard AI,ChatGPT,GitHub Copilot;Tabnine,GitHub Copilot,Stack Overflow;Stack Exchange,A few times per month or weekly,Not sure/can't remember,NaN,"No, not really",NaN,Yes,Indifferent,Greater efficiency,Somewhat distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
89159,89160,I agree,None of these,Prefer not to say,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [438]:
df['CompTotal'].nlargest(10)

56322    5.000000e+46
18463    1.000000e+21
49553    1.000000e+16
43556    1.000000e+16
35779    1.000000e+15
15439    4.567887e+12
33078    1.000000e+11
19679    2.239672e+10
56853    1.980000e+10
9175     1.840199e+10
Name: CompTotal, dtype: float64

In [439]:
df['CompTotal'].nsmallest(10)

4350     0.0
56111    0.0
60083    0.0
4465     0.0
26478    0.0
30461    0.0
37641    0.0
49933    0.0
65647    0.0
73797    0.0
Name: CompTotal, dtype: float64

In [440]:
df.nlargest(10,'CompTotal')

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
56322,56323,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Boots...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,More than 50 years,More than 50 years,Blockchain,"10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Bahamas,AED United Arab Emirates dirham,5.000000e+46,Ada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,"No, not at all",SEX,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
18463,18464,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,NaN,NaN,11,8,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+21,Bash/Shell (all shells);Python,Bash/Shell (all shells);Go;JavaScript;Python,PostgreSQL;Redis,Elasticsearch;MongoDB;PostgreSQL;Redis,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud,FastAPI,FastAPI,NaN,NaN,Composer;Docker,Composer;Docker,IPython;PyCharm;Vim,IPython;PyCharm;Vim,Ubuntu,Ubuntu,Jira;Trello,Jira;Trello,Discord;Google Meet;Jitsi;Skype;Slack;Telegram...,Discord;Google Meet;Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,11.0,Strongly agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,6-10 times a week,NaN,30-60 minutes a day,30-60 minutes a day,Microservices;Continuous integration (CI) and ...,NaN,Appropriate in length,Easy,NaN
49553,49554,I agree,"I am not primarily a developer, but I write co...",25-34,"Employed, full-time",In-person,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,22,5,Research & Development role,"1,000 to 4,999 employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.000000e+16,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,CUDA;GTK;NumPy;Pandas;Qt;Scikit-Learn;TensorFl...,CMake;Docker;Make;MSVC;Ninja;Pip,CMake;LLVM's Clang;Make;Pip,Notepad++;Spyder;Vim;Visual Studio Code,Notepad++;Spyder;Vim;Visual Studio Code,Debian;Windows,Red Hat;Windows,Markdown File;Redmine,Markdown File;Redmine,Microsoft Teams,Microsoft Teams,WolframAlpha,ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",It would be most helpful if the AI could delet...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Continuous i...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN
43556,43557,I agree,I am a developer by profession,18-24,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Pluralsight,8,4,"Developer, desktop or enterprise applications",500 to 999 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,Romania,RON\tRomanian leu,1.000000e+16,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,BigQuery;Cosmos DB;Elasticsearch;MariaDB;Micro...,NaN,Amazon Web Services (AWS);Microsoft Azure;VMware,Microsoft Azure;VMware,ASP.NET;ASP.NET CORE,NaN,.NET (5+) ;GTK;MFC;Opencv;OpenGL;Qt,GTK;MFC;Opencv;OpenGL;Qt,Ant;APT;Boost.Test;CMake;cppunit;Dagger;Docker...,Boost.Test;CMake;cppunit;GNU GCC;LLVM's Clang;...,Atom;Code::Blocks;Kate;Nano;Notepad++;Qt Creat...,Kate;Qt Creator;Visual Studio,Cygwin;Ubuntu;Windows,Ubuntu,GitHub Discussions;Markdown File,GitHub Discussions,IRC;Microsoft Teams;Skype,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Less than once per month or monthly,Yes,Less than once per month or monthly,Neutral,don't,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
35779,35780,I agree,I am a developer by profession,25-34,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Pluralsight;Coursera;Udacity,10,7,NaN,20 to 99 employees,I have a great deal of influence,Investigate,Ask developers I know/work with;Visit develope...,Canada,CAD\tCanadian dollar,1.000000e+15,Assembly;Bash/Shell (all shells);C#;C++;Cobol;...,HTML/CSS;SQL;TypeScript,Cloud Firestore;Elasticsearch;MariaDB;Microsof...,MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,Angular;AngularJS;ASP.NET;ASP.NET CORE;Deno;Ex...,Angular;NestJS,Electron,NaN,Chocolatey;CMake;Composer;Docker;Gradle;npm;We...,Docker;npm,Android Studio;Atom;Eclipse;Goland;IntelliJ ID...,Visual Studio Code,Android;Ubuntu;Windows;Windows Subsystem for L...,Android;Red Hat;Ubuntu;Windows;Windows Subsyst...,Azure Devops;Confluence;Jira;Markdown File;Trello,NaN,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,none,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
15439,15440,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,School or academic work,"Associate degree (A.A., A.S., etc.)",Friend or family member,NaN,NaN,4,2,Data or business analyst,20 to 99 employees,I have a great deal of influence,Other,Read ratings or reviews on third party sites l...,Pakistan,KES\tKenyan shilling,4.567887e+12,Apex,Ada,BigQuery,NaN,Amazon Web Services (AWS);Cloudflare;Colocatio...,Managed Hosting;Oracle Cloud Infrastructure (OCI),Angular;AngularJS;ASP.NET;ASP.NET CORE;Blazor;...,NaN,NaN,NaN,Dagger,Dagger,Android Studio,NaN,AIX,NaN,Adobe Workfront,NaN,Cisco Webex Teams,NaN,Andi,NaN,NaN,NaN,Collectives on Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,Gvmhmko,"No, but I plan to soon",Indifferent,NaN,Neither trust nor distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,16.0,Neither agree nor disagree,Strongly disagree,Neither agree nor disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times a week,30-60 minutes a day,Over 120 minutes a day,Continuous integration (CI) and (more often) c...,NaN,Appropriate in length,NaN,NaN
33078,33079,I agree,I am a developer by profession,25-34,"Independent contractor, freelancer, or self-em...",Remote,Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Formal documentation provided by the owner of ...,NaN,11,8,"Developer, full-stack",2 to 9 employees,I have a great deal of influence,Given a list,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+11,HTML/CSS;JavaScript;Kotlin;PHP;Python,Dart;HTML/CSS;JavaScript;Kotlin;PHP;Python,MySQL;SQLite,MySQL;SQLite,NaN,NaN,Express;jQuery;Laravel;Next.js;Node.js;React,Express;jQuery;Laravel;Next.js;Node.js;React,Qt,Qt,NaN,NaN,Android Studio;Atom;Notepad++;PhpStorm;Qt Crea...,Android Studio;Atom;Notepad++;PhpStorm;Qt Crea...,Windows,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",NaN,Yes,Very favorable,Increase productivity;Speed up learning,Somewhat trust,Learning about a codebase;Project planning;Wri...,Learning about a codebase;Project planning;Wri...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,2362249.0
19679,19680,I agree,I am a developer by profession,25-34,"Employed, part-time",Remote,Professional development or self-paced learnin...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,9,3,Developer Experience,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,NaN,Other (please specify):,Mali,XOF\tWest African CFA franc,2.239672e+10,Ada,Ada,BigQuery,BigQuery,Amazon Web Services (AWS),Amazon Web Services (AWS),Angular,Angular,.NET (5+),.NET (5+),Ansible,Ansible,Android Studio,Android Studio,AIX,AIX,Adobe Workfront,Adobe Workfront,Cisco Webex Teams,Cisco Webex Teams,Andi,Andi,Adrenaline,Adrenaline,Collectives on Stack Overflow,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,Neutral,Profossionnal,Yes,Very favorable,Other (please explain),Highly trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,36573181.0
56853,56854,I agree,"I am not primarily a developer, but I write co...",18-24,"Employed, full-time;Independent contractor, fr...",Remote,Hobby;Contribute to open-source projects;Boots...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Other;edX;Pluralsight;Coursera,12,7,"Developer, QA or test","Just me - I am a freelancer, sole proprietor, ...",I have some influence,Investigate,Ask developers I know/work with;Visit develope...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.980000e+10,Bash/Shell (all shells);Go;HTML/CSS;JavaScript...,Bash/Shell (all shells);Go;HTML/CSS;Python;Rus...,MariaDB;MySQL;PostgreSQL;Redis;SQLite,Clickhouse;MariaDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Cloudflare;Digital O...,Cloudflare;Hetzner;Microsoft Azure;Scaleway,Express;Flask;Next.js;Node.js;React;Vue.js,FastAPI;Flask;Next.js;React;Svelte,NaN,NaN,Ansible;APT;Docker;npm;Pip;Webpack;Yarn,Ansible;APT;Docker;Make;Nix;Pip;Yarn,Vim;Visual Studio Code;VSCodium;WebStorm,Vim;Visual Studio Code;VSCodium,Android;Arch;Debian;MacOS;Other Linux-based,Debian;iOS;MacOS;Other Linux-based,Clickup;Confluence;Jira;Markdown File;Miro;Mon...,Markdown File;Miro;Notion;Wikis,Discord;Google Meet;Telegram,Google Meet;Telegram,ChatGPT;You.com,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Collectives on S...,Daily or almost daily,Yes,Daily or almost daily,"Yes, somewhat","It's not mature enough yet, Maybe it can be us...","No, but I plan to soon",Indifferent,NaN,Highly distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,7.0,Disagree,Disagree,Disagree,Neither agree nor disagree,Agree,Disagree,Agree,Agree,1-2 times a week,1-2 times a week,Never,60-120 minutes a day,15-30 minutes a day,Automated testing;Continuous integration (CI) ...,"Information Services, IT, Software Development...",Appropriate in length,Neither easy nor difficult,467725.0
9175,9176,I agree,I am a developer by profession,25-34,"Employed, full-time",Remote,Hobby,Primary/elementary school,Colleague,NaN,NaN,NaN,NaN,Academic researcher,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,NaN,Start a free trial,Bangladesh,BDT\tBangladeshi taka,1.840199e+10,Ada,NaN,BigQuery,NaN,Amazon Web Services (AWS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android Studio,Android Studio,Other (Please Specify):,Other (Please Specify):,NaN,NaN,Coolfire Core;Discord;Google Chat;Google Meet;...,Coolfire Core;Discord;Google Chat;Google Meet;...,NaN,NaN,NaN,NaN,Collectives on Stack Overflow,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",NaN,Yes,Very favorable,Increase productivity,Highly trust,NaN,Learning about a codebase,NaN,Learning about a codebase,NaN,NaN,NaN,NaN,Yes,People manager,20.0,Strongly disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Never,Never,NaN,Less than 15 minutes a day,Less than 15 minutes a day,Innersource initiative,NaN,Too short,NaN,NaN

Aggregate & join

In [441]:
df['CompTotal'].describe()

count    4.822500e+04
mean     1.036807e+42
std      2.276847e+44
min      0.000000e+00
25%      6.300000e+04
50%      1.150000e+05
75%      2.300000e+05
max      5.000000e+46
Name: CompTotal, dtype: float64

In [442]:
df['CompTotal'].max()

np.float64(4.999999999999999e+46)

In [443]:
df.groupby('Country')[['RemoteWork','YearsCode']].count()

                                      RemoteWork  YearsCode
Country
Afghanistan                                   42         59
Albania                                       50         56
Algeria                                       50         82
Andorra                                       13         15
Angola                                         9         11
...                                          ...        ...
Venezuela, Bolivarian Republic of...          87        106
Viet Nam                                     265        381
Yemen                                         17         20
Zambia                                        18         26
Zimbabwe                                      17         33

[185 rows x 2 columns]

In [444]:
df.groupby('Country')['Employment'].value_counts()

Country      Employment
Afghanistan  Employed, full-time                                                                                           22
             Independent contractor, freelancer, or self-employed                                                           8
             Not employed, but looking for work                                                                             5
             I prefer not to say                                                                                            5
             Student, full-time                                                                                             4
                                                                                                                           ..
Zimbabwe     Not employed, but looking for work;Employed, part-time                                                         1
             Student, part-time;Not employed, and not looking for work                                                      1
             Employed, full-time;Not employed, but looking for work                                                         1
             Independent contractor, freelancer, or self-employed;Student, full-time;Employed, part-time                    1
             Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Student, full-time     1
Name: count, Length: 2880, dtype: int64

In [445]:
df.groupby('Country')['Employment'].value_counts()['India'].sort_values(ascending = False)

Employment
Employed, full-time                                                                                                               3273
Student, full-time                                                                                                                 800
Independent contractor, freelancer, or self-employed                                                                               290
Not employed, but looking for work                                                                                                 270
Employed, full-time;Independent contractor, freelancer, or self-employed                                                           193
                                                                                                                                  ...
Employed, full-time;Student, full-time;Employed, part-time                                                                           1
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, but looking for work                          1
Independent contractor, freelancer, or self-employed;Not employed, but looking for work;Not employed, and not looking for work       1
Employed, full-time;Not employed, but looking for work;Student, part-time                                                            1
Not employed, but looking for work;Not employed, and not looking for work                                                            1
Name: count, Length: 59, dtype: int64

In [446]:
df[df['Employment']== 'Employed, full-time'].groupby('Country')['ConvertedCompYearly'].agg(['min','max'])

                                          min        max
Country
Afghanistan                              33.0  9203683.0
Albania                                  14.0   139700.0
Algeria                                 512.0    37776.0
Andorra                               23560.0   289142.0
Angola                                  662.0     7942.0
...                                       ...        ...
Venezuela, Bolivarian Republic of...      5.0   180000.0
Viet Nam                                  1.0   107090.0
Yemen                                  9000.0    59917.0
Zambia                                 4036.0    41122.0
Zimbabwe                               3000.0   114000.0

[176 rows x 2 columns]

can you guess what percent of people in each country knows python

In [447]:
df

,ResponseId,Q120,MainBranch,Age,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,TechList,BuyNewTool,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,AISearchHaveWorkedWith,AISearchWantToWorkWith,AIDevHaveWorkedWith,AIDevWantToWorkWith,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,SOAI,AISelect,AISent,AIAcc,AIBen,AIToolInterested in Using,AIToolCurrently Using,AIToolNot interested in Using,AINextVery different,AINextNeither different nor similar,AINextSomewhat similar,AINextVery similar,AINextSomewhat different,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,ProfessionalTech,Industry,SurveyLength,SurveyEase,ConvertedCompYearly
56322,56323,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,Hobby;Contribute to open-source projects;Boots...,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Other (please specify):,NaN,NaN,More than 50 years,More than 50 years,Blockchain,"10,000 or more employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,Bahamas,AED United Arab Emirates dirham,5.000000e+46,Ada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,"No, not at all",SEX,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
18463,18464,I agree,I am a developer by profession,25-34,"Employed, full-time",In-person,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Friend or fam...,NaN,NaN,11,8,"Developer, back-end",20 to 99 employees,I have a great deal of influence,Investigate,Start a free trial;Ask developers I know/work ...,"Iran, Islamic Republic of...",IRR\tIranian rial,1.000000e+21,Bash/Shell (all shells);Python,Bash/Shell (all shells);Go;JavaScript;Python,PostgreSQL;Redis,Elasticsearch;MongoDB;PostgreSQL;Redis,Amazon Web Services (AWS),Amazon Web Services (AWS);Google Cloud,FastAPI,FastAPI,NaN,NaN,Composer;Docker,Composer;Docker,IPython;PyCharm;Vim,IPython;PyCharm;Vim,Ubuntu,Ubuntu,Jira;Trello,Jira;Trello,Discord;Google Meet;Jitsi;Skype;Slack;Telegram...,Discord;Google Meet;Skype;Telegram;Whatsapp,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per week,"Yes, somewhat",NaN,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,People manager,11.0,Strongly agree,Neither agree nor disagree,Agree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Strongly agree,Never,6-10 times a week,NaN,30-60 minutes a day,30-60 minutes a day,Microservices;Continuous integration (CI) and ...,NaN,Appropriate in length,Easy,NaN
49553,49554,I agree,"I am not primarily a developer, but I write co...",25-34,"Employed, full-time",In-person,I don’t code outside of work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Books / Physical media;Colleague;On the job tr...,Formal documentation provided by the owner of ...,NaN,22,5,Research & Development role,"1,000 to 4,999 employees",I have some influence,Investigate,Start a free trial;Ask developers I know/work ...,United States of America,USD\tUnited States dollar,1.000000e+16,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,Bash/Shell (all shells);C;C++;Fortran;Julia;MA...,NaN,NaN,NaN,NaN,NaN,NaN,NumPy;Pandas,CUDA;GTK;NumPy;Pandas;Qt;Scikit-Learn;TensorFl...,CMake;Docker;Make;MSVC;Ninja;Pip,CMake;LLVM's Clang;Make;Pip,Notepad++;Spyder;Vim;Visual Studio Code,Notepad++;Spyder;Vim;Visual Studio Code,Debian;Windows,Red Hat;Windows,Markdown File;Redmine,Markdown File;Redmine,Microsoft Teams,Microsoft Teams,WolframAlpha,ChatGPT;Google Bard AI;WolframAlpha,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",It would be most helpful if the AI could delet...,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,11.0,Agree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,3-5 times a week,1-2 times a week,30-60 minutes a day,30-60 minutes a day,DevOps function;Automated testing;Continuous i...,"Information Services, IT, Software Development...",Appropriate in length,Easy,NaN
43556,43557,I agree,I am a developer by profession,18-24,"Employed, full-time",Remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Online Courses or Certi...,Formal documentation provided by the owner of ...,Pluralsight,8,4,"Developer, desktop or enterprise applications",500 to 999 employees,I have little or no influence,NaN,Start a free trial;Ask developers I know/work ...,Romania,RON\tRomanian leu,1.000000e+16,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,Assembly;Bash/Shell (all shells);C;C#;C++;F#;J...,BigQuery;Cosmos DB;Elasticsearch;MariaDB;Micro...,NaN,Amazon Web Services (AWS);Microsoft Azure;VMware,Microsoft Azure;VMware,ASP.NET;ASP.NET CORE,NaN,.NET (5+) ;GTK;MFC;Opencv;OpenGL;Qt,GTK;MFC;Opencv;OpenGL;Qt,Ant;APT;Boost.Test;CMake;cppunit;Dagger;Docker...,Boost.Test;CMake;cppunit;GNU GCC;LLVM's Clang;...,Atom;Code::Blocks;Kate;Nano;Notepad++;Qt Creat...,Kate;Qt Creator;Visual Studio,Cygwin;Ubuntu;Windows,Ubuntu,GitHub Discussions;Markdown File,GitHub Discussions,IRC;Microsoft Teams;Skype,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow f...,Less than once per month or monthly,Yes,Less than once per month or monthly,Neutral,don't,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
35779,35780,I agree,I am a developer by profession,25-34,I prefer not to say,NaN,NaN,Something else,Books / Physical media;Colleague;Friend or fam...,Formal documentation provided by the owner of ...,Codecademy;Udemy;Pluralsight;Coursera;Udacity,10,7,NaN,20 to 99 employees,I have a great deal of influence,Investigate,Ask developers I know/work with;Visit develope...,Canada,CAD\tCanadian dollar,1.000000e+15,Assembly;Bash/Shell (all shells);C#;C++;Cobol;...,HTML/CSS;SQL;TypeScript,Cloud Firestore;Elasticsearch;MariaDB;Microsof...,MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS);Cloudflare;Digital O...,NaN,Angular;AngularJS;ASP.NET;ASP.NET CORE;Deno;Ex...,Angular;NestJS,Electron,NaN,Chocolatey;CMake;Composer;Docker;Gradle;npm;We...,Docker;npm,Android Studio;Atom;Eclipse;Goland;IntelliJ ID...,Visual Studio Code,Android;Ubuntu;Windows;Windows Subsystem for L...,Android;Red Hat;Ubuntu;Windows;Windows Subsyst...,Azure Devops;Confluence;Jira;Markdown File;Trello,NaN,Cisco Webex Teams;Discord;Google Chat;Google M...,Discord,ChatGPT,NaN,GitHub Copilot,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Neutral,none,"No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88883,88884,I agree,I am a developer by profession,18-24,"Employed, full-time",Remote,Freelance/contract work,"Secondary school (e.g. American high school, G...",Friend or family member,NaN,NaN,NaN,NaN,Other (please specify):,10 to 19 employees,I have a great deal of influence,Given a list,Ask developers I know/work with,Antigua and Barbuda,AOA\tAngolan kwanza,NaN,Ada;Clojure;Cobol,Apex;APL;Assembly;Bash/Shell (all shells);C;C#,BigQuery,NaN,NaN,NaN,WordPress,NaN,.NET MAUI,NaN,NaN,NaN,NaN,NaN,NaN,AIX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,A few times per month or weekly,No,NaN,Neutral,"Create a chat bot like chat gpt , to get answe...",Yes,Very favorable,Increase productivity,Highly trust,Project planning;Documenting code,Learning about a codebase;Project planning;Wri...,NaN,Learning about a codebase;Project planning;Wri...,NaN,NaN,NaN,NaN,Yes,People manager,50.0,Disagree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6-10 times a week,3-5 times a week,3-5 times a week,30-60 minutes a day,30-60 minutes a day,Microservices,Financial Services,Appropriate in length,NaN,NaN
88940,88941,I agree,I am learning to code,Under 18,NaN,NaN,NaN,Something else,"Other online resources (e.g., videos, blogs, f...","How-to videos;Online challenges (e.g., daily o...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,Chile,NaN,NaN,HTML/CSS;Python;SQL,C#,NaN,NaN,NaN,NaN,Node.js,NaN,NaN,NaN,npm,NaN,Visual Studio Code,NaN,Windows,NaN,NaN,NaN,Discord;Telegram;Whatsapp,NaN,ChatGPT,NaN,NaN,NaN,I have never visited Stack Overflow or the Sta...,NaN,No,NaN,"No, not at all",NaN,"No, but I plan to soon",NaN,NaN,Somewhat trust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN
89028,89029,I agree,None of these,45-54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89134,89135,I agree,I code primarily as a hobby,Under 18,"Student, full-time",NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,Bash/Shell (all shells);C;C++;Elixir;Go;Haskel...,Assembly;Bash/Shell (all shells);C;Clojure;Eli...,Cloud Firestore;Dynamodb;Firebase Realtime Dat...,Cassandra;Cockroachdb;Elasticsearch;MongoDB;Ne...,Amazon Web Services (AWS);Cloudflare;Digital O...,Amazon Web Services (AWS);Cloudflare;Google Cl...,Angular;Deno;Django;Express;Flask;Next.js;Node...,Angular;FastAPI;Fastify;Next.js;Node.js;Nuxt.j...,Electron;Keras;NumPy;Opencv;Pandas;Qt;SwiftUI;...,Hadoop;Ionic;Keras;NumPy;Opencv;Pandas;SwiftUI...,Ansible;APT;Cargo;Docker;GNU GCC;Make;npm;Terr...,Ansible;APT;Cargo;Docker;GNU GCC;Kubernetes;Ma...,Neovim;Vim;Xcode,Neovim;Vim;Xcode,MacOS,MacOS,Airtable;Markdown File;Notion,Markdown File;Notion,Discord;Google Chat;Google Meet;Zoom,Discord,ChatGPT;Google Bard AI,ChatGPT,GitHub Copilot;Tabnine,GitHub Copilot,Stack Overflow;Stack Exchange,A few times per month or weekly,Not sure/can't remember,NaN,"No, not really",NaN,Yes,Indifferent,Greater efficiency,Somewhat distrust,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
89159,89160,I agree,None of these,Prefer not to say,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [448]:
df.groupby(['Country'])['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('Python').value_counts(normalize = True))

Country
Afghanistan  False    0.656250
             True     0.343750
Albania      False    0.683333
             True     0.316667
Algeria      False    0.588235
                        ...
Yemen        True     0.400000
Zambia       False    0.576923
             True     0.423077
Zimbabwe     True     0.558824
             False    0.441176
Name: LanguageHaveWorkedWith, Length: 349, dtype: float64

In [449]:
df[df['Country'] == 'Afghanistan']['LanguageHaveWorkedWith'].nunique()

56

In [450]:
residents_per_country = df.groupby('Country')['ResponseId'].count()
python_per_country = df.groupby('Country')['LanguageHaveWorkedWith'].apply(lambda x : x.str.contains('Python').sum())

In [452]:
final_df = pd.concat([residents_per_country,python_per_country],axis = 1,ignore_index=False,keys = ['Total Residents','Python Knowm']).reset_index()
final_df['% Known'] = (final_df['Python Knowm']/final_df['Total Residents'])*100

In [ ]:
final_df

,Country,Total Residents,Python Knowm,% Known
0,Afghanistan,64,22,34.375000
1,Albania,60,19,31.666667
2,Algeria,85,35,41.176471
3,Andorra,16,5,31.250000
4,Angola,13,4,30.769231
...,...,...,...,...
180,"Venezuela, Bolivarian Republic of...",106,42,39.622642
181,Viet Nam,390,174,44.615385
182,Yemen,20,8,40.000000
183,Zambia,26,11,42.307692
184,Zimbabwe,34,19,55.882353

In [ ]:
df['mean_per_country'] = df.groupby('Country')['CompTotal'].transform('mean')

df[['Country','ResponseId','CompTotal','mean_per_country']]

,Country,ResponseId,CompTotal,mean_per_country
56322,Bahamas,56323,5.000000e+46,5.000000e+46
18463,"Iran, Islamic Republic of...",18464,1.000000e+21,4.255319e+18
49553,United States of America,49554,1.000000e+16,8.395602e+11
43556,Romania,43557,1.000000e+16,2.439024e+13
35779,Canada,35780,1.000000e+15,4.734850e+11
...,...,...,...,...
88883,Antigua and Barbuda,88884,NaN,3.500000e+06
88940,Chile,88941,NaN,2.546286e+07
89028,NaN,89029,NaN,NaN
89134,United States of America,89135,NaN,8.395602e+11
89159,NaN,89160,NaN,NaN

In [ ]:
df.groupby('Country').filter(lambda x : x['CompTotal'].mean()> 500000000000000000)[['Country', 'CompTotal']]

                            Country     CompTotal
56322                       Bahamas  5.000000e+46
18463  Iran, Islamic Republic of...  1.000000e+21
33078  Iran, Islamic Republic of...  1.000000e+11
56853  Iran, Islamic Republic of...  1.980000e+10
75523  Iran, Islamic Republic of...  1.600000e+10
...                             ...           ...
12555  Iran, Islamic Republic of...           NaN
23567  Iran, Islamic Republic of...           NaN
33276  Iran, Islamic Republic of...           NaN
35692  Iran, Islamic Republic of...           NaN
78050  Iran, Islamic Republic of...           NaN

[579 rows x 2 columns]

Handling None values

In [ ]:
people = {
    'first' : ['Corey','Jane','John','Chris',np.nan,None,'NA'],
    'last' : ['Schafer','Doe','Doe','Schafer',np.nan,np.nan,'Missing'],
    'email' : ['CoreyMSchafer@gmail.com','JaneDoe@gmail.com','JohnDoe@gmail.com',None,np.nan,'Anonymous@gmail.com','NA'],
    'age' : ['33','55','63','36',None,None,'Missing']
}

df_pep = pd.DataFrame(people)
df_pep

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       55
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
4    NaN      NaN                      NaN      NaN
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [ ]:
df_pep.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       55
2   John      Doe        JohnDoe@gmail.com       63
6     NA  Missing                       NA  Missing

In [ ]:
df_pep.dropna(axis='index',how = 'any')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       55
2   John      Doe        JohnDoe@gmail.com       63
6     NA  Missing                       NA  Missing

In [ ]:
df_pep.dropna(axis='index',how = 'all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       55
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
5    NaN      NaN      Anonymous@gmail.com      NaN
6     NA  Missing                       NA  Missing

In [ ]:
df_pep.dropna(axis='index',how = 'any' , subset = ['first'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@gmail.com       55
2   John      Doe        JohnDoe@gmail.com       63
3  Chris  Schafer                      NaN       36
6     NA  Missing                       NA  Missing

In [ ]:
df_pep.replace({'NA' : np.nan, "Missing" : np.nan},inplace= True)

   first     last                    email  age
0  Corey  Schafer  CoreyMSchafer@gmail.com   33
1   Jane      Doe        JaneDoe@gmail.com   55
2   John      Doe        JohnDoe@gmail.com   63
3  Chris  Schafer                      NaN   36
4    NaN      NaN                      NaN  NaN
5    NaN      NaN      Anonymous@gmail.com  NaN
6    NaN      NaN                      NaN  NaN

In [ ]:
df_pep.dropna(axis='index',how = 'any' , subset = ['first'])

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@gmail.com  55
2   John      Doe        JohnDoe@gmail.com  63
3  Chris  Schafer                      NaN  36

In [ ]:
df_pep.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [ ]:
df_pep.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@gmail.com  55
2   John      Doe        JohnDoe@gmail.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@gmail.com   0
6      0        0                        0   0

Casting

In [ ]:
type(np.nan)

float

In [ ]:
df_pep['age'] = df_pep['age'].astype(float)
df_pep

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33.0
1   Jane      Doe        JaneDoe@gmail.com  55.0
2   John      Doe        JohnDoe@gmail.com  63.0
3  Chris  Schafer                      NaN  36.0
4    NaN      NaN                      NaN   NaN
5    NaN      NaN      Anonymous@gmail.com   NaN
6    NaN      NaN                      NaN   NaN

In [453]:
df_pep['age'].mean()

np.float64(46.75)

DateSeries

In [457]:
str = '2020-03-13 06-PM'
dt = pd.to_datetime(str,format='%Y-%m-%d %I-%p')
print(dt)

2020-03-13 18:00:00

In [458]:
dt.day_name()

'Friday'